import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import { useEffect, useState } from 'react';

const inter = Inter({ subsets: ['latin'] });
type Data = {
  name: string;
  age: number;
  id: string;
};

export default function Home() {
  const [data, setData] = useState<Data[]>();
  const [loading, setLoading] = useState(false);
  useEffect(() => {
    const nextAPi = async () => {
      setLoading(true);
      const res = await fetch('http://localhost:3000/api/hello/');
      const data = await res.json();
      setData(data);
      setLoading(false);
    };
    nextAPi();
  }, []);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          {loading ? (
            <h1>Loading...</h1>
          ) : (
            <div className={styles.grid}>
              {data?.map((item) => (
                <div key={item.id} className={styles.card}>
                  <h1>Nome: {item.name}</h1>
                  <h1>Idade: {item.age}</h1>
                </div>
              ))}
            </div>
          )}
        </div>
      </main>
    </>
  );
}
