import Head from 'next/head';
import { useRouter } from 'next/router';
import styles from '@/styles/Home.module.css';
import { useState } from 'react';
import useDynamicDataQuery from '../../queries/dynamicQueryData';
import useEditDataMutation from '../../queries/editMutation';
const EditUser = () => {
  const router = useRouter();
  const { pid } = router.query;
  const [name, setName] = useState('');
  const [age, setAge] = useState(0);
  const [id, setId] = useState(pid);
  const { isLoading, data } = useDynamicDataQuery(pid as string);
  const { editDataMutation } = useEditDataMutation(id as string);
  const handleSubmit = () => {
    setId(data.id);
    console.log('name', name);
    editDataMutation.mutateAsync({ name, age });
    router.push('/');
  };

  return (
    <>
      <Head>
        <title>Editar </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {!isLoading && (
          <>
            <h1 className={styles.title}>Edite o usuário {data.name}</h1>
            <div className={styles.card}>
              <div className={styles.formContainer}>
                <label htmlFor="name">Nome</label>
                <input
                  type="text"
                  name="name"
                  id="name"
                  placeholder={data.name}
                  onChange={(e) => setName(e.target.value)}
                />
                <label htmlFor="age">Idade</label>
                <input
                  type="text"
                  name="age"
                  id="age"
                  placeholder={data.age}
                  onBlur={(e) => setAge(Number(e.target.value))}
                />
              </div>
              <button
                type="button"
                onClick={() => {
                  handleSubmit();
                }}
                className={styles.buttonForm}
              >
                Editar
              </button>
            </div>
          </>
        )}
      </main>
    </>
  );
};
export default EditUser;
